In [1]:
import numpy as np


In [5]:
# 计算贝塞尔曲线上的点
def bezier_curve(points, num_segments):
    t = np.linspace(0, 1, num=num_segments)
    curve = np.zeros((num_segments, 2))
    for i in range(num_segments):
        curve[i] = (1 - t[i]) ** 3 * points[0] + 3 * (1 - t[i]) ** 2 * t[i] * points[1] + 3 * (1 - t[i]) * t[i] ** 2 * points[2] + t[i] ** 3 * points[3]
    return curve

# 定义控制点
points = np.array([[-0.8, -0.8], [-0.4, 0.4], [0.4, -0.4], [0.8, 0.8]])

# 计算曲线上的100个点
curve = bezier_curve(points, 10)

curve


array([[-0.8       , -0.8       ],
       [-0.65294925, -0.46858711],
       [-0.48285322, -0.25240055],
       [-0.2962963 , -0.11851852],
       [-0.09986283, -0.0340192 ],
       [ 0.09986283,  0.0340192 ],
       [ 0.2962963 ,  0.11851852],
       [ 0.48285322,  0.25240055],
       [ 0.65294925,  0.46858711],
       [ 0.8       ,  0.8       ]])

In [2]:
import numpy as np
direction = np.array((-1., 0., 0.))
(np.sign(direction) + 1).astype(int)

array([0, 1, 1])

In [5]:
np.array([1,2,3])*np.array([1,1,1])

array([1, 2, 3])

In [9]:
(np.sign((10,0,0)) + 1).astype(int)

array([2, 1, 1])

In [11]:
np.argmax([1,0,0])

0

In [12]:
np.dot([1,0,1], [1,2,1])

2

In [5]:
points = [[1,2], [3,4]]
points[:1] *= 2
points


[[1, 2], [1, 2], [3, 4]]

In [7]:
a = np.array([[1,2,3],[4,5,6]])
(3, *a.shape[1:])

(3, 3)

In [11]:
np.resize(a, (1, 3))

array([[1, 2, 3]])

In [1]:
"".join(["hello", "world"])

'helloworld'

In [1]:
import  numpy as np
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [6]:
import copy

original = [[1, 2, 3], [4, 5, 6]]

# Shallow Copy
shallow = copy.copy(original)

# Deep Copy
deep = copy.deepcopy(original)

print("Original: ", original)
print("Shallow: ", shallow)
print("Deep: ", deep)

original[0][1] = 'two'

print("Original: ", original)
print("Shallow: ", shallow)
print("Deep: ", deep)

Original:  [[1, 2, 3], [4, 5, 6]]
Shallow:  [[1, 2, 3], [4, 5, 6]]
Deep:  [[1, 2, 3], [4, 5, 6]]
Original:  [[1, 'two', 3], [4, 5, 6]]
Shallow:  [[1, 'two', 3], [4, 5, 6]]
Deep:  [[1, 2, 3], [4, 5, 6]]


In [1]:
import copy

original = [[1, 2, 3], [4, 5, 6]]

# Shallow Copy
shallow = copy.copy(original)

# Deep Copy
deep = copy.deepcopy(original)

print("Original: ", original)
print("Shallow: ", shallow)
print("Deep: ", deep)

original[0][1] = 'two'

print("Original: ", original)
print("Shallow: ", shallow)
print("Deep: ", deep)

Original:  [[1, 2, 3], [4, 5, 6]]
Shallow:  [[1, 2, 3], [4, 5, 6]]
Deep:  [[1, 2, 3], [4, 5, 6]]
Original:  [[1, 'two', 3], [4, 5, 6]]
Shallow:  [[1, 'two', 3], [4, 5, 6]]
Deep:  [[1, 2, 3], [4, 5, 6]]
