In [10]:
import numpy as np


In [2]:
import numpy as np
direction = np.array((-1., 0., 0.))
(np.sign(direction) + 1).astype(int)

array([0, 1, 1])

In [5]:
np.array([1,2,3])*np.array([1,1,1])

array([1, 2, 3])

In [9]:
(np.sign((10,0,0)) + 1).astype(int)

array([2, 1, 1])

In [11]:
np.argmax([1,0,0])

0

In [12]:
np.dot([1,0,1], [1,2,1])

2

In [5]:
points = [[1,2], [3,4]]
points[:1] *= 2
points


[[1, 2], [1, 2], [3, 4]]